name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda #v3.4.2
      - run: |
          LIBRARIAN_RELEASE=true ./gradlew librarianPublishToMavenCentral
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_GPG_KEY_PASSWORD }}
